name: e_commerce_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  card_swiper: ^3.0.1
  dio: ^5.4.1
  flutter:
    sdk: flutter
  get_it: ^7.6.7
  injectable: ^2.3.2
  intl: ^0.19.0
  logger: ^2.0.2+1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  injectable_generator: ^2.4.1

flutter:
  uses-material-design: true
flutter_intl:
  enabled: true
